on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore Saverr/Saverr.csproj

      - name: Build project
        run: dotnet build Saverr/Saverr.csproj --configuration Release --no-restore

      - name: Publish EXE
        run: dotnet publish Saverr/Saverr.csproj --configuration Release --output ./publish --self-contained true -r win-x64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./publish/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
